name: Update README Folder Tree

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Update README.md with folder structure
        run: python update_tree.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "mnoukhej"
          git config --global user.email "mnoukhej@gmail.com"

          git add README.md
          git diff-index --quiet HEAD || git commit -m "🔄 Auto-update folder structure in README.md"

          git config commit.gpgsign true || true
          git push
